### ISSUE TITLE
Output verbosity

### ISSUE THREAD

**Issue by Spy-Seth** [ryan953/flow-annotation-check#36]
Hi,

First of all: thanks for this great tool! We use it into our CI to check the presence/absence of the flow header on our code. 

In our project it validate ~500 files and print the result on the output. This is a _lot_ of output. When a file is invalid we have to scroll all this output to find witch files is not valid.

We were thinking about an options that only list errored files: `--only-show-error`, or `--summary` 

What did you think about this?

**Comment by ryan953** [comment]
This is a great idea! Lets do it

There is also `--summarize-only` flag that was added in the most-recent diff, so if those two worked together that'd be incredible.
What do you think if we changed the names of both these flags to remove the `-only` part? Then it'd make a little more sense to read when they're both used.

I'm thinking along the lines of: `flow-annotation-check --list-files noflow --show-summary ~/path/to/project`

The options would be: `--list-files [all|flow|noflow|flowweak|none]` with a default of `all` and then `--show-summary` as an extra flag to add the summary section. So we could just show the summary by doing `--list-files none --show-summary` or do the summary and just the non-flow files (includes flow-weak) with `--list-files noflow --show-summary`.

**Comment by Spy-Seth** [comment]
This seems to be a really good way to implement this 👍

**Comment by ryan953** [comment]
See #37

**Comment by Spy-Seth** [comment]
Ho perfect! Thanks you for this 👍
