### ISSUE TITLE
Enforce flow strict check

### ISSUE THREAD

**Issue by DavidBabel** [ryan953/flow-annotation-check#78]
Hey guys, 

Thanks for your module, it's very helpfull.
I wonder fi there is a way to enforce the check of "// @flow strict" on the beginning of each files, and exit with an error on the CLI when it's not the case ?

I'm not sure if the option exists yet, i cannot find.

Bye

**Comment by ryan953** [comment]
I don't think this is possible with the cli flags the way they are right now. `--allow-weak` does a similar thing, but it's not broad enough to cover `strict` and `strict-local`. 

In the short-term it's possible to look at the summary output in your favorite format and see if a non-zero number of files are listed in the non-strict categories. 

It seems the integrity of the file goes up as we move from `no flow > weak > flow > strict-local > strict`so maybe a flag like `--level=[noflow|weak|flow|strict-local|strict]` maps that idea clearly. We could add some aliases too like `--require-strict` or `--require-strict-local` to round it out. Defining it more than once could result in the strictest setting being used.

- `--level=noflow` would be new, we'd never exit with code 1 anymore
- `--level=weak` would be the same as `--allow-weak`
- `--level=flow` would be the same as the current defaults
- `--level=strict-local` would require `@flow strict-local` or `@flow strict`
- `--level=strict` would require the use of `@flow strict` only

I'll put that together too to look at. Would that solve the problem for you?

**Comment by ryan953** [comment]
Alright, we just pushed out v1.10.0 with the `--level` flag in there.

It's got everything I laid out above, we should be able to call `npm flow-annotation-check --level=flowstrict` or update the package.json with `{ "flow-annotation-check": { "level": "flowstrict" } }` to enforce `// @flow strict` at the start of each file!

Let me know if it's working for your repo @DavidBabel or if there's anything I missed let me know and we'll re-open this. Thanks again for your question/suggestion!
