### ISSUE TITLE
Example exclude is ambigous

### ISSUE THREAD

**Issue by DavidBabel** [ryan953/flow-annotation-check#79]
Hey hi, 

I tried to use your `"-x"` option, but it's very confusing for me.
The documentation present an array as default value, but to expect the same behaviour as default i tried may ways to make it works : 

```bash
flow-annotation-check -x '+(node_modules|build|flow-typed)/**/*.js'
flow-annotation-check -x 'src/assets/js/**/*.js'
flow-annotation-check -x '+(node_modules|build|flow-typed)/**/*.js' -x 'src/assets/js/**/*.js'
flow-annotation-check -x '+(node_modules|build|flow-typed|src/assets/js)/**/*.js'
flow-annotation-check -x '+(node_modules|build|flow-typed)/**/*.js|+(src/assets/js)/**/*.js'
```
And anytime i tried to manage with this string, the exclude option is fully ignored.

The winner is : 
```bash
flow-annotation-check -x '+(node_modules|build|flow-typed)/**/*.js' -x 'src/assets/js/**/*.js'
```

But it was very unexpected.

**Comment by ryan953** [comment]
Hey @DavidBabel 

Ya, that does seem confusing now that I'm back reading the docs for `--exclude`... and `--include` too.

The way it works under the hood is that each item in that array is passed into [isaacs/node-glob](https://github.com/isaacs/node-glob) library and we get a list of files back. We combine all the lists from all the globs and voila!
The idea is that if people (like me) don't want to make a complex pattern like your last two then they can pass in more patterns and get the same effect.

I'll go in and update the docs to be clearer about how the CLI arguments can work, and try to get an example too. Give me a few to put up a change!

**Comment by ryan953** [comment]
@DavidBabel let me know if the changes in #80 are clearer for us.

[README.md preview](https://github.com/ryan953/flow-annotation-check/blob/05466fda85791f278e82aefcb684d9083c4bdd01/README.md)

**Comment by ryan953** [comment]
Woo! Thanks for the feedback and the great examples btw
